#include "/Engine/Public/Platform.ush"

Buffer<float3> VertexBuffer : register(t0);
RWStructuredBuffer<float3> OutputBuffer : register(u0);

uint NumVertices;
float3 FixedTransform;

[numthreads(64, 1, 1)]
void Voxelization(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    const uint VertexIdx = DispatchThreadID.x;
    if (VertexIdx < NumVertices) OutputBuffer[VertexIdx] = VertexBuffer[VertexIdx];
}